/*
 * Copyright (c) 2020 Mercedes-Benz. All rights reserved.
 */
package cc.iteck.rm.exception;

import lombok.Getter;
import org.springframework.http.HttpStatus;

import static org.springframework.http.HttpStatus.*;

@Getter
public enum ErrorCode {

    CALL_FINANCE_INIT_QUOTATION_FAILED(INTERNAL_SERVER_ERROR),
    CALL_FINANCE_SEQUENCE_QUOTATION_FAILED(INTERNAL_SERVER_ERROR),
    CALL_FINANCE_PRODUCT_DESCRIPTION_FAILED(INTERNAL_SERVER_ERROR),
    CALL_FINANCE_VAP_DESCRIPTION_FAILED(INTERNAL_SERVER_ERROR),
    CALL_FINANCE_SAVE_QUOTATION_FAILED(INTERNAL_SERVER_ERROR),

    GET_JSON_FROM_FILE_FAILED(INTERNAL_SERVER_ERROR),

    PARSE_OBJECT_LIST_FROM_JSON(INTERNAL_SERVER_ERROR),
    PARSE_JSON_FAILED(INTERNAL_SERVER_ERROR),
    PARSE_OBJECT_TO_STRING_FAILED(INTERNAL_SERVER_ERROR),
    NOT_FOUND_EXCEPTION(NOT_FOUND),
    BAD_REQUEST_EXCEPTION(BAD_REQUEST),
    HTTP_REQUEST_FAILED(INTERNAL_SERVER_ERROR),
    READ_FILE_FAILED(INTERNAL_SERVER_ERROR),
    GET_CLIENT_IP_FAILED(INTERNAL_SERVER_ERROR);

    private final HttpStatus status;

    ErrorCode(HttpStatus status) {
        this.status = status;
    }
}
