# DataSource Config
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://database:5432/require_manager
      username: postgres
      password: postgres
      tomcat:
        test-on-borrow: true
        validation-query: SELECT 1
        test-while-idle: true
        time-between-eviction-runs-millis: 3600000
